stages:
  - info
  - build

variables:
  GIT_STRATEGY: 'clone'
  COMPILE: 'false'

info:
  stage: info
  script:
    - echo "This is your first stage (ãƒ„)"
    - echo "Username is ${USERNAME} with ${PASSWORD}"

build_application:
  stage: build
  tags:
    - build
    - mobiliar
  image: registry.access.redhat.com/ubi9/openjdk-17:latest
  script:
    - ./gradlew assemble
